wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702753479.176227
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 5
      - 23
      - 24
      4: 3.11.7
      5: 0.15.8
      8:
      - 5
